### ISSUE TITLE
include ORICD API into config-mapping

### ISSUE THREAD

**Issue by csae8092** [acdh-oeaw/arche-ref-sources#10]
https://info.orcid.org/documentation/features/public-api/

**Comment by zozlak** [comment]
Added a simple config for ORCID: https://github.com/acdh-oeaw/arche-ref-sources/blob/master/config-sample.yaml#L74-L101

The limitation is the raw-LOD usage of orcid URIs (trying to resolve them with the HTTP accept header set to some RDF format) seems to return only partial information (especially the affiliation data is missing).
